//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDiarista.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDiarista.Resource.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot já cadastrado.
        /// </summary>
        public static string ErroBotJaCadastrado {
            get {
                return ResourceManager.GetString("ErroBotJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot não está cadastrado.
        /// </summary>
        public static string ErroBotNaoCadastrado {
            get {
                return ResourceManager.GetString("ErroBotNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique os campos obrigatórios.
        /// </summary>
        public static string ErroCamposObrigatorios {
            get {
                return ResourceManager.GetString("ErroCamposObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade já está cadastrada.
        /// </summary>
        public static string ErroEntidadeJaCadastrada {
            get {
                return ResourceManager.GetString("ErroEntidadeJaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade não está cadastrada.
        /// </summary>
        public static string ErroEntidadeNaoCadastrada {
            get {
                return ResourceManager.GetString("ErroEntidadeNaoCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível gerar token.
        /// </summary>
        public static string ErroGerarToken {
            get {
                return ResourceManager.GetString("ErroGerarToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado para a geração do token.
        /// </summary>
        public static string ErroGerarTokenUsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroGerarTokenUsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenção já está cadastrada.
        /// </summary>
        public static string ErroIntencaoJaCadastrada {
            get {
                return ResourceManager.GetString("ErroIntencaoJaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenção não está cadastrada.
        /// </summary>
        public static string ErroIntencaoNaoCadastrada {
            get {
                return ResourceManager.GetString("ErroIntencaoNaoCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenção não cadastrada no LUIS..
        /// </summary>
        public static string ErroIntencaoNaoCadastradaNoLuis {
            get {
                return ResourceManager.GetString("ErroIntencaoNaoCadastradaNoLuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar executar a solicitação.
        /// </summary>
        public static string ErroInternoNaAPI {
            get {
                return ResourceManager.GetString("ErroInternoNaAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item recebido é inválido.
        /// </summary>
        public static string ErroItemRecebidoInvalido {
            get {
                return ResourceManager.GetString("ErroItemRecebidoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicação Luis já está cadastrada.
        /// </summary>
        public static string ErroLuisJaCadastrado {
            get {
                return ResourceManager.GetString("ErroLuisJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicação Luis não está cadastrada.
        /// </summary>
        public static string ErroLuisNaoCadastrado {
            get {
                return ResourceManager.GetString("ErroLuisNaoCadastrado", resourceCulture);
            }
        }
    }
}
